services:
  db:
    restart: unless-stopped

  backend:
    restart: unless-stopped

  identity-access-service:
    restart: unless-stopped

  frontend:
    restart: unless-stopped

  gateway:
    restart: unless-stopped
