import { type CSSProperties, type FormEvent, useCallback, useEffect, useRef, useState } from 'react'
import { NavLink, useNavigate, useParams } from 'react-router-dom'
import { api } from './api'
import { useAuth } from './auth'
import type { ApplicationView, LeaseView, PropertyHomeView, PropertyView, ReportDetail, ReportJobView } from './api/contracts'
import { ApiError } from './api/contracts'
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusPill, formatDate, formatMoney, statusLabels } from './components'

function useLoad<T>(load: () => Promise<T>) {
  const [value, setValue] = useState<T>(); const [error, setError] = useState<unknown>(); const [loading, setLoading] = useState(true)
  const run = useCallback(() => { setLoading(true); setError(undefined); void load().then(setValue).catch(setError).finally(() => setLoading(false)) }, [load])
  useEffect(() => { const task = window.setTimeout(run, 0); return () => window.clearTimeout(task) }, [run])
  return { value, error, loading, retry: run, setValue }
}

function PropertyArt({ property, large = false }: { property: PropertyView; large?: boolean }) { return <div className={`property-art ${property.accent} ${large ? 'large' : ''}`} role="img" aria-label={`${property.address} 房源示意图`}><span className="sun" /><span className="building one" /><span className="building two" /><span className="window w1" /><span className="window w2" /><span className="tree">♣</span><span className="art-label">{property.reference}</span></div> }

export function PropertiesPage() {
  const load = useCallback(() => api.listProperties(), []); const { value, error, loading, retry } = useLoad(load); const [query, setQuery] = useState(''); const [bedrooms, setBedrooms] = useState(0)
  const filtered = value?.filter((property) => `${property.address} ${property.suburb}`.toLowerCase().includes(query.toLowerCase()) && property.bedrooms >= bedrooms) ?? []
  return <><PageHeader eyebrow="公开房源" title="找到适合你的下一处住所" description="访客与所有客户身份均可浏览公开、正在招租的房源。" /><section className="search-panel"><label className="search-box"><span>⌕</span><input aria-label="搜索区域或地址" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索区域或地址" /></label><label>最少卧室<select value={bedrooms} onChange={(event) => setBedrooms(Number(event.target.value))}><option value="0">不限</option><option value="1">1+</option><option value="2">2+</option><option value="3">3+</option></select></label><button className="button">搜索房源</button></section>{loading ? <LoadingState /> : error ? <ErrorState error={error} onRetry={retry} /> : filtered.length === 0 ? <EmptyState title="没有匹配房源" description="换个区域或筛选条件试试。" /> : <section><div className="section-heading"><h2>{filtered.length} 套可查看房源</h2><span>按最新更新排序</span></div><div className="property-grid">{filtered.map((property) => <article className="property-card" key={property.id}><PropertyArt property={property} /><div className="property-body"><div className="property-title"><div><h3>{property.address}</h3><p>{property.suburb}</p></div><StatusPill status={property.availability} /></div><div className="facts"><span>▣ {property.bedrooms} 卧</span><span>◫ {property.bathrooms} 卫</span><span>▱ {property.parking} 车位</span></div><footer><b>{formatMoney(property.weeklyRent)}<small> / 周</small></b><NavLink className="arrow-link" to={`/properties/${property.id}`}>查看详情 →</NavLink></footer></div></article>)}</div></section>}</>
}

export function PropertyDetailPage() {
  const { id = '' } = useParams(); const load = useCallback(() => api.getProperty(id), [id]); const { value: property, error, loading, retry } = useLoad(load); const { bootstrap, has } = useAuth(); const navigate = useNavigate(); const [message, setMessage] = useState('你好，我想进一步了解这套房源。'); const [notice, setNotice] = useState(''); const [caseId, setCaseId] = useState(''); const [busy, setBusy] = useState(false)
  if (loading) return <LoadingState />; if (error || !property) return <ErrorState error={error ?? new ApiError(404, 'resource_not_found', '没有找到房源')} onRetry={retry} />
  async function contact() { if (!bootstrap?.customer) { navigate('/login', { state: { from: `/properties/${id}` } }); return } setBusy(true); try { const result = await api.contactProperty(property!.id, message); setCaseId(result.caseId); setNotice(`留言已提交，案件编号 ${result.caseId}`) } catch (caught) { setNotice(caught instanceof Error ? caught.message : '提交失败') } finally { setBusy(false) } }
  return <><NavLink className="back-link" to="/properties">← 返回房源列表</NavLink><div className="detail-hero"><PropertyArt property={property} large /><section><span className="eyebrow">{property.reference} · {property.availability === 'available' ? '可申请' : '申请处理中'}</span><h1>{property.address}</h1><p>{property.suburb}</p><div className="facts large"><span>{property.bedrooms}<small>卧室</small></span><span>{property.bathrooms}<small>浴室</small></span><span>{property.parking}<small>车位</small></span></div><strong>{formatMoney(property.weeklyRent)}<small> / 周</small></strong></section></div><div className="detail-columns"><article className="surface prose"><h2>房源介绍</h2><p>{property.description}</p><h3>房源配置</h3><div className="feature-list">{property.features.map((feature) => <span key={feature}>✓ {feature}</span>)}</div></article><aside className="surface action-card"><span className="eyebrow">下一步</span><h2>对这套房源感兴趣？</h2><p>先给真人业务员留言。提交申请前需要建立房源联系案件。</p><label>留言<textarea value={message} onChange={(event) => setMessage(event.target.value)} /></label><button className="button full" disabled={busy} onClick={() => void contact()}>{busy ? '提交中…' : bootstrap?.customer ? '联系业务员' : '登录后联系'}</button>{notice ? <p className="notice" role="status">{notice}</p> : null}<button className="button secondary full" disabled={!has('application:create') || !caseId} onClick={() => navigate(`/applications/new?property=${property.id}&case=${caseId}`)}>{!has('application:create') ? '当前身份不可申请' : caseId ? '提交租房申请' : '请先联系业务员'}</button></aside></div></>
}

export function ApplicationsPage() {
  const load = useCallback(() => api.listApplications(), []); const { value = [], error, loading, retry } = useLoad(load); const { has } = useAuth()
  return <><PageHeader eyebrow="个人业务" title="我的申请" description="查看申请进度与公开决策状态。内部审核记录不会在此展示。" action={has('application:create') ? <NavLink className="button" to="/properties">浏览房源</NavLink> : undefined} />{loading ? <LoadingState /> : error ? <ErrorState error={error} onRetry={retry} /> : value.length === 0 ? <EmptyState title="还没有租房申请" description="从公开房源详情联系业务员后即可开始申请。" action={<NavLink className="button" to="/properties">浏览房源</NavLink>} /> : <div className="list-stack">{value.map((application) => <NavLink to={`/applications/${application.id}`} className="list-row" key={application.id}><div className="list-symbol">□</div><div className="grow"><span className="eyebrow">{application.reference}</span><h3>{application.property.address}</h3><p>{application.property.suburb} · 期望入住 {formatDate(application.desiredStartOn)}</p></div><StatusPill status={application.status} /><span className="chevron">›</span></NavLink>)}</div>}{!has('application:create') ? <p className="permission-note">Tenant 可读取全部本人历史申请，但不能创建或修改申请。</p> : null}</>
}

export function ApplicationDetailPage() {
  const { id = '' } = useParams(); const load = useCallback(() => api.getApplication(id), [id]); const { value, error, loading, retry } = useLoad(load)
  if (loading) return <LoadingState />; if (error || !value) return <ErrorState error={error ?? new ApiError(404, 'resource_not_found', '没有找到申请')} onRetry={retry} />
  const steps = ['submitted', 'reviewing', 'approved']; const current = Math.max(0, steps.indexOf(value.status))
  return <><NavLink className="back-link" to="/applications">← 返回我的申请</NavLink><PageHeader eyebrow={value.reference} title={value.property.address} action={<StatusPill status={value.status} />} /><div className="surface application-detail"><h2>申请进度</h2><div className="timeline">{steps.map((step, index) => <div className={index <= current ? 'done' : ''} key={step}><span>{index < current ? '✓' : index + 1}</span><b>{statusLabels[step]}</b><small>{index === 0 ? formatDate(value.submittedAt) : index === current ? '当前阶段' : '等待处理'}</small></div>)}</div><div className="data-grid"><div><small>期望入住</small><b>{formatDate(value.desiredStartOn)}</b></div><div><small>租期</small><b>{value.termMonths} 个月</b></div><div><small>入住人数</small><b>{value.occupants} 人</b></div><div><small>最后更新</small><b>{formatDate(value.updatedAt)}</b></div></div>{value.note ? <div className="note-box"><small>申请说明</small><p>{value.note}</p></div> : null}</div></>
}

export function NewApplicationPage() {
  const navigate = useNavigate(); const params = new URLSearchParams(location.search); const propertyId = params.get('property') ?? ''; const caseId = params.get('case') ?? ''; const [error, setError] = useState<unknown>(); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { const application = await api.createApplication({ propertyId, caseId, desiredStartOn: String(data.get('start')), termMonths: Number(data.get('term')), occupants: Number(data.get('occupants')), note: String(data.get('note')) }); navigate(`/applications/${application.id}`) } catch (caught) { setError(caught) } finally { setBusy(false) } }
  return <><NavLink className="back-link" to={`/properties/${propertyId}`}>← 返回房源</NavLink><PageHeader eyebrow="租房申请" title="提交基本租住信息" description="申请将关联你与业务员的现有联系案件。" /><form className="surface form-card" onSubmit={submit}>{error ? <ErrorState error={error} /> : null}<div className="form-grid"><label>期望入住日期<input name="start" type="date" required defaultValue="2026-10-01" /></label><label>租期<select name="term" defaultValue="12"><option value="6">6 个月</option><option value="12">12 个月</option><option value="18">18 个月</option></select></label><label>入住人数<input name="occupants" type="number" min="1" max="8" defaultValue="1" required /></label></div><label>补充说明<textarea name="note" placeholder="告诉业务员你的入住计划（选填）" /></label><label className="check"><input type="checkbox" required /> 我确认以上信息真实，并同意提交审核</label><button className="button" disabled={busy}>{busy ? '正在提交…' : '提交申请'}</button></form></>
}

function LeaseSummary({ lease }: { lease: LeaseView }) { return <section className="lease-banner"><div><span className="eyebrow">当前租约 · {lease.reference}</span><h2>{lease.property.address}</h2><p>{lease.property.suburb}</p></div><div className="lease-dates"><span><small>租期开始</small>{formatDate(lease.startsOn)}</span><span>→</span><span><small>租期结束</small>{formatDate(lease.endsOn)}</span></div><div><StatusPill status={lease.status} /><strong>{formatMoney(lease.weeklyRent)}<small>/周</small></strong></div></section> }

function HomeSections({ home, historical = false, onMaintenance }: { home: PropertyHomeView; historical?: boolean; onMaintenance?: () => void }) {
  const { has } = useAuth(); const active = home.lease.status === 'active' && !historical; const [contractOpen, setContractOpen] = useState(false)
  return <><LeaseSummary lease={home.lease} />{home.lease.status === 'executed' ? <div className="info-banner"><b>合同已执行，等待入住</b><span>起租日为 {formatDate(home.lease.startsOn)}。合同和房产信息可查看；维修与视频报告会在 Lease 变为 active 后开放。</span></div> : null}<div className="dashboard-grid"><section className="surface module-card"><header><div><span className="module-icon">⌘</span><h2>租赁合同</h2></div><StatusPill status={home.lease.status} /></header><p>合同版本 v{home.lease.document.version} · {home.lease.document.termsDigest}</p><button className="button secondary" onClick={() => setContractOpen(true)}>查看合同</button></section><section className="surface module-card"><header><div><span className="module-icon">$</span><h2>缴费记录</h2></div><span>{home.invoices.length} 条</span></header>{home.invoices.length ? home.invoices.map((invoice) => <div className="mini-row" key={invoice.id}><span>{invoice.period}<small>{formatMoney(invoice.amount)}</small></span><StatusPill status={invoice.status} /></div>) : <p>暂无缴费记录</p>}</section><section className="surface module-card"><header><div><span className="module-icon">⚒</span><h2>维修申请</h2></div><span>{home.maintenance.length} 条</span></header>{home.maintenance.length ? home.maintenance.map((order) => <div className="mini-row" key={order.id}><span>{order.summary}<small>{order.reference}</small></span><StatusPill status={order.status} /></div>) : <p>{active ? '当前没有维修申请' : '此阶段不开放维修'}</p>}{has('maintenance:create') && active ? <button className="button secondary" onClick={onMaintenance}>提交维修申请</button> : null}</section><section className="surface module-card"><header><div><span className="module-icon">◉</span><h2>视频安全报告</h2></div><span>{home.reports.length} 份</span></header>{home.reports.length ? home.reports.map((item) => <NavLink className="mini-row link" key={item.id} to={`/reports/${item.id}`}><span>{item.title}<small>{formatDate(item.completedAt)}</small></span><StatusPill status={item.status === 'active' ? 'completed' : item.status} /></NavLink>) : <p>{active ? '尚未生成报告' : '此阶段不开放报告'}</p>}{has('report:create') && active ? <NavLink className="button secondary" to="/reports/new">生成视频报告</NavLink> : null}</section></div>{contractOpen ? <ContractDialog lease={home.lease} historical={historical} onClose={() => setContractOpen(false)} /> : null}</>
}

function ContractDialog({ lease, historical, onClose }: { lease: LeaseView; historical: boolean; onClose: () => void }) { return <div className="dialog-backdrop" role="presentation"><section className="dialog contract-dialog" role="dialog" aria-modal="true" aria-labelledby="contract-title"><button className="dialog-close" aria-label="关闭" onClick={onClose}>×</button><span className="eyebrow">合同 {lease.reference}</span><h2 id="contract-title">住宅租赁合同</h2><div className="data-grid"><div><small>房产</small><b>{lease.property.address}</b></div><div><small>租期</small><b>{formatDate(lease.startsOn)} — {formatDate(lease.endsOn)}</b></div><div><small>租金</small><b>{formatMoney(lease.weeklyRent)} / 周</b></div><div><small>合同版本</small><b>v{lease.document.version}</b></div></div><div className="note-box"><small>条款摘要</small><p>{lease.document.termsDigest}</p><p>本页面为 P0 产品确认与只读展示，不代表第三方法律电子签章。</p></div>{historical ? <p className="permission-note">历史合同只读，不可修改或重新签署。</p> : null}<button className="button full" onClick={onClose}>关闭</button></section></div> }

export function MyPropertyPage() {
  const { bootstrap, has } = useAuth(); const former = bootstrap?.customer?.status === 'former_tenant'; const activeLeaseCapabilities = has('report:create') || has('maintenance:create'); const load = useCallback((): Promise<LeaseView[] | PropertyHomeView> => { if (former) return api.listLeases(); if (activeLeaseCapabilities) return api.getCurrentProperty(); return api.getCurrentProperty() }, [former, activeLeaseCapabilities]); const { value, error, loading, retry, setValue } = useLoad(load); const [showMaintenance, setShowMaintenance] = useState(false)
  if (loading) return <LoadingState />; if (error) return <ErrorState error={error} onRetry={retry} />
  if (former) { const leases = value as LeaseView[]; return <><PageHeader eyebrow="历史租住" title="我的房子" description="历史合同和该租期报告永久只读；不能新建维修或报告。" />{leases.length ? <div className="list-stack">{leases.map((lease) => <NavLink className="list-row" to={`/leases/${lease.id}/property`} key={lease.id}><div className="list-symbol">◇</div><div className="grow"><span className="eyebrow">{lease.reference}</span><h3>{lease.property.address}</h3><p>{formatDate(lease.startsOn)} — {formatDate(lease.endsOn)}</p></div><StatusPill status={lease.status} /><span className="chevron">›</span></NavLink>)}</div> : <EmptyState title="没有历史租约" description="你的历史租住记录会显示在这里。" />}</> }
  const home = value as PropertyHomeView; return <><PageHeader eyebrow="租住中心" title="我的房子" description="合同、缴费、维修与报告都集中在这里。" /><HomeSections home={home} onMaintenance={() => setShowMaintenance(true)} />{showMaintenance ? <MaintenanceDialog onClose={() => setShowMaintenance(false)} onCreated={(order) => setValue({ ...home, maintenance: [order, ...home.maintenance] })} /> : null}</>
}

export function HistoricalPropertyPage() { const { leaseId = '' } = useParams(); const load = useCallback(() => api.getHistoricalProperty(leaseId), [leaseId]); const { value, error, loading, retry } = useLoad(load); if (loading) return <LoadingState />; if (error || !value) return <ErrorState error={error ?? new Error('没有记录')} onRetry={retry} />; return <><NavLink className="back-link" to="/my-property">← 返回历史房源</NavLink><PageHeader eyebrow="只读历史" title={value.lease.property.address} description="只有与这份历史 Lease 相同 source_lease_id 的报告会显示。" /><HomeSections home={value} historical /></> }

function MaintenanceDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (order: PropertyHomeView['maintenance'][number]) => void }) { const [error, setError] = useState<unknown>(); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { onCreated(await api.createMaintenance(String(data.get('summary')), String(data.get('description')), String(data.get('priority')) as 'low' | 'normal' | 'urgent')); onClose() } catch (caught) { setError(caught) } finally { setBusy(false) } } return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="maintenance-title"><button className="dialog-close" aria-label="关闭" onClick={onClose}>×</button><span className="eyebrow">Active Lease</span><h2 id="maintenance-title">提交维修申请</h2>{error ? <ErrorState error={error} /> : null}<form onSubmit={submit}><label>问题摘要<input name="summary" required placeholder="例如：浴室水龙头滴水" /></label><label>详细说明<textarea name="description" placeholder="何时发生、影响范围等" /></label><label>优先级<select name="priority" defaultValue="normal"><option value="low">低</option><option value="normal">普通</option><option value="urgent">紧急</option></select></label><button className="button full" disabled={busy}>{busy ? '提交中…' : '提交维修申请'}</button></form></section></div> }

export function NewReportPage() {
  const { has } = useAuth(); const navigate = useNavigate(); const fileRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [attributes, setAttributes] = useState<Record<string, boolean>>({ isPregnant: false, isChildren: false, isElderly: false, isDisabled: false, isAllergic: false, isPets: false }); const [job, setJob] = useState<ReportJobView>(); const [error, setError] = useState<unknown>(); const [running, setRunning] = useState(false)
  async function run() { if (!file) { setError(new ApiError(422, 'validation_error', '请先选择视频文件')); return } setRunning(true); setError(undefined); try { const detail = await api.startReport(file, attributes, setJob); navigate(`/reports/${detail.id}`) } catch (caught) { setError(caught) } finally { setRunning(false) } }
  if (!has('report:create')) return <ErrorState error={new ApiError(403, 'report_generation_not_allowed', '只有 active Tenant 可以创建当前房产报告')} />
  const labels: Record<string, string> = { isPregnant: '孕妇', isChildren: '儿童', isElderly: '老人', isDisabled: '行动不便', isAllergic: '过敏', isPets: '宠物' }
  return <><NavLink className="back-link" to="/my-property">← 返回我的房子</NavLink><PageHeader eyebrow="原视频分析流程" title="生成房屋安全报告" description="视频经 Tenant Portal BFF 流式上传；房产与 Lease 由服务端从唯一 active Lease 推导。" /><div className="report-workspace"><section className="surface upload-panel"><h2>1. 选择房屋视频</h2><button className="drop-zone" onClick={() => fileRef.current?.click()} disabled={running}><span>↥</span><b>{file ? file.name : '选择 video/* 文件'}</b><small>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB` : '支持常见视频格式'}</small></button><input ref={fileRef} hidden type="file" accept="video/*" onChange={(event) => setFile(event.target.files?.[0])} /><h2>2. 住户情况</h2><div className="chip-grid">{Object.entries(labels).map(([key, label]) => <button type="button" className={attributes[key] ? 'chip active' : 'chip'} key={key} onClick={() => setAttributes((current) => ({ ...current, [key]: !current[key] }))}>{attributes[key] ? '✓ ' : ''}{label}</button>)}</div>{error ? <ErrorState error={error} /> : null}<button className="button full" disabled={running} onClick={() => void run()}>{running ? '正在分析…' : '上传并开始分析'}</button></section><aside className="surface progress-panel"><span className="eyebrow">Workflow</span><h2>分析进度</h2><div className="progress-ring" style={{ '--progress': `${job?.progressPercent ?? 0}%` } as CSSProperties}><span>{job?.progressPercent ?? 0}<small>%</small></span></div><h3>{job ? statusLabels[job.stage] ?? job.stage.replaceAll('_', ' ') : '等待开始'}</h3><p>关闭页面不会取消已提交任务。真实模式可使用持久 job ID 恢复。</p>{job ? <small>Job {job.id}</small> : null}</aside></div></>
}

export function ReportDetailPage() { const { id = '' } = useParams(); const load = useCallback(() => api.getReport(id), [id]); const { value, error, loading, retry } = useLoad(load); if (loading) return <LoadingState />; if (error || !value) return <ErrorState error={error ?? new Error('没有报告')} onRetry={retry} />; return <><NavLink className="back-link" to="/my-property">← 返回我的房子</NavLink><PageHeader eyebrow="视频安全报告" title={value.title} description={`完成于 ${formatDate(value.completedAt)}`} action={<StatusPill status={value.status === 'active' ? 'completed' : value.status} />} /><section className="report-summary"><div><span>✓</span><h2>报告概览</h2><p>{value.overview}</p></div><div><small>校验结果</small><b>{value.validationPassed ? '通过' : '需复核'}</b><small>客户投影不展示模型诊断与内部对象信息</small></div></section><div className="region-grid">{value.regions.map((region, index) => <article className="surface region-card" key={region.name}><header><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{region.name}</h2><StatusPill status={region.risk} /></div></header><h3>观察结果</h3><ul>{region.findings.map((item) => <li key={item}>{item}</li>)}</ul><h3>建议</h3><ul className="suggestions">{region.suggestions.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></> }

export function AgentPage() { return <><PageHeader eyebrow="导航占位" title="SafeScan Agent" description="Agent 不参与 P0 的确定性租赁主链路。" /><EmptyState title="Agent 即将上线" description="本迭代只保留导航入口，不提供对话或自动化业务能力。房源、申请、合同、维修和报告请使用对应页面。" /></> }
export function ProfilePage() { const { bootstrap } = useAuth(); const customer = bootstrap?.customer; return <><PageHeader eyebrow="账户" title="个人资料" description="身份阶段来自 Identity 与 BFF，前端不能自行修改。" /><section className="surface profile-card"><span className="avatar large">{customer?.username.slice(0, 1)}</span><div><h2>{customer?.username}</h2><p>{customer?.email}</p></div><div className="profile-status"><small>客户身份</small><StatusPill status={customer?.status ?? 'guest'} /><small>状态版本 {bootstrap?.statusVersion}</small></div></section></> }
