BEGIN;
CREATE SCHEMA identity_access;


CREATE TABLE identity_access.organizations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	name TEXT NOT NULL, 
	code TEXT NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	timezone TEXT DEFAULT 'Asia/Shanghai' NOT NULL, 
	PRIMARY KEY (id), 
	CHECK (status IN ('active','suspended')), 
	UNIQUE (code)
)

;


CREATE TABLE identity_access.account_memberships (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	user_id BIGINT NOT NULL, 
	persona TEXT NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	CHECK (persona IN ('staff','tenant','prospect')), 
	CHECK (status IN ('active','inactive')), 
	UNIQUE (organization_id, user_id, persona)
)

;


CREATE TABLE identity_access.permissions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	description TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	UNIQUE (organization_id, code)
)

;


CREATE TABLE identity_access.roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	UNIQUE (organization_id, code)
)

;


CREATE TABLE identity_access.staff (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	user_id BIGINT, 
	staff_code TEXT NOT NULL, 
	display_name TEXT NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	CHECK (status IN ('active','inactive')), 
	UNIQUE (organization_id, staff_code), 
	UNIQUE (organization_id, user_id)
)

;


CREATE TABLE identity_access.role_permissions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	permission_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	FOREIGN KEY(organization_id, role_id) REFERENCES identity_access.roles (organization_id, id), 
	FOREIGN KEY(organization_id, permission_id) REFERENCES identity_access.permissions (organization_id, id), 
	UNIQUE (organization_id, role_id, permission_id)
)

;

CREATE INDEX ix_role_permissions_permission_id ON identity_access.role_permissions (organization_id, permission_id);

CREATE INDEX ix_role_permissions_role_id ON identity_access.role_permissions (organization_id, role_id);


CREATE TABLE identity_access.staff_roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	staff_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	FOREIGN KEY(organization_id, staff_id) REFERENCES identity_access.staff (organization_id, id), 
	FOREIGN KEY(organization_id, role_id) REFERENCES identity_access.roles (organization_id, id), 
	UNIQUE (organization_id, staff_id, role_id)
)

;

CREATE INDEX ix_staff_roles_role_id ON identity_access.staff_roles (organization_id, role_id);

CREATE INDEX ix_staff_roles_staff_id ON identity_access.staff_roles (organization_id, staff_id);
COMMIT;
