BEGIN;
CREATE SCHEMA inspection_report;


CREATE TABLE inspection_report.inspections (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	inspector_id BIGINT, 
	kind TEXT NOT NULL, 
	inspected_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	status TEXT DEFAULT 'scheduled' NOT NULL, 
	summary TEXT DEFAULT '' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (kind IN ('routine','move_in','move_out','video')), 
	CHECK (status IN ('scheduled','completed','cancelled'))
)

;

CREATE INDEX ix_inspections_inspector_id ON inspection_report.inspections (organization_id, inspector_id);

CREATE INDEX ix_inspections_lookup ON inspection_report.inspections (organization_id, property_id, inspected_at);

CREATE INDEX ix_inspections_property_id ON inspection_report.inspections (organization_id, property_id);


CREATE TABLE inspection_report.inspection_findings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	inspection_id BIGINT NOT NULL, 
	area TEXT NOT NULL, 
	description TEXT NOT NULL, 
	severity TEXT NOT NULL, 
	evidence JSONB DEFAULT '[]'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, inspection_id) REFERENCES inspection_report.inspections (organization_id, id), 
	CHECK (severity IN ('info','low','medium','high','critical'))
)

;

CREATE INDEX ix_inspection_findings_inspection_id ON inspection_report.inspection_findings (organization_id, inspection_id);


CREATE TABLE inspection_report.inspection_reports (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	inspection_id BIGINT NOT NULL, 
	report_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, inspection_id) REFERENCES inspection_report.inspections (organization_id, id), 
	UNIQUE (organization_id, inspection_id, report_id)
)

;

CREATE INDEX ix_inspection_reports_inspection_id ON inspection_report.inspection_reports (organization_id, inspection_id);


CREATE TABLE inspection_report.report_jobs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	requested_by_user_id BIGINT NOT NULL, 
	input_file_id BIGINT NOT NULL, 
	report_id BIGINT, 
	inspection_id BIGINT, 
	status TEXT DEFAULT 'queued' NOT NULL, 
	validation_passed BOOLEAN, 
	idempotency_key TEXT NOT NULL, 
	pipeline_version TEXT NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, inspection_id) REFERENCES inspection_report.inspections (organization_id, id), 
	CHECK (status IN ('queued','running','completed','failed','cancelled')), 
	UNIQUE (organization_id, requested_by_user_id, idempotency_key)
)

;

CREATE INDEX ix_report_jobs_inspection_id ON inspection_report.report_jobs (organization_id, inspection_id);


CREATE TABLE inspection_report.report_job_steps (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	job_id BIGINT NOT NULL, 
	step_name TEXT NOT NULL, 
	attempt INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	metrics JSONB DEFAULT '{}'::jsonb NOT NULL, 
	error_code TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, job_id) REFERENCES inspection_report.report_jobs (organization_id, id), 
	CHECK (status IN ('running','completed','failed','skipped')), 
	UNIQUE (organization_id, job_id, step_name, attempt), 
	CHECK (attempt > 0)
)

;

CREATE INDEX ix_report_job_steps_job_id ON inspection_report.report_job_steps (organization_id, job_id);
COMMIT;
