BEGIN;
CREATE SCHEMA knowledge;


CREATE TABLE knowledge.knowledge_bases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	name TEXT NOT NULL, 
	audience TEXT DEFAULT 'staff' NOT NULL, 
	retrieval_provider TEXT NOT NULL, 
	external_dataset_id TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (audience IN ('staff','tenant','public')), 
	UNIQUE (organization_id, code)
)

;


CREATE TABLE knowledge.knowledge_documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	knowledge_base_id BIGINT NOT NULL, 
	document_key TEXT NOT NULL, 
	version INTEGER NOT NULL, 
	title TEXT NOT NULL, 
	file_id BIGINT, 
	external_document_id TEXT, 
	status TEXT DEFAULT 'draft' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, knowledge_base_id) REFERENCES knowledge.knowledge_bases (organization_id, id), 
	CHECK (status IN ('draft','published','retired')), 
	UNIQUE (organization_id, knowledge_base_id, document_key, version), 
	CHECK (version > 0)
)

;

CREATE INDEX ix_knowledge_documents_knowledge_base_id ON knowledge.knowledge_documents (organization_id, knowledge_base_id);


CREATE TABLE knowledge.knowledge_role_access (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	knowledge_base_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, knowledge_base_id) REFERENCES knowledge.knowledge_bases (organization_id, id), 
	UNIQUE (organization_id, knowledge_base_id, role_id)
)

;

CREATE INDEX ix_knowledge_role_access_knowledge_base_id ON knowledge.knowledge_role_access (organization_id, knowledge_base_id);

CREATE INDEX ix_knowledge_role_access_role_id ON knowledge.knowledge_role_access (organization_id, role_id);
COMMIT;
