BEGIN;
CREATE SCHEMA maintenance;


CREATE TABLE maintenance.maintenance_drafts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	task_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	created_by BIGINT NOT NULL, 
	summary TEXT NOT NULL, 
	priority TEXT DEFAULT 'medium' NOT NULL, 
	mode TEXT DEFAULT 'mock' NOT NULL, 
	status TEXT DEFAULT 'simulated' NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (priority IN ('low','medium','high','urgent')), 
	CHECK (mode IN ('mock','live')), 
	CHECK (status IN ('simulated','draft','submitted','discarded')), 
	UNIQUE (organization_id, idempotency_key), 
	CHECK (mode != 'mock' OR status IN ('simulated','discarded'))
)

;

CREATE INDEX ix_maintenance_drafts_created_by ON maintenance.maintenance_drafts (organization_id, created_by);

CREATE INDEX ix_maintenance_drafts_property_id ON maintenance.maintenance_drafts (organization_id, property_id);

CREATE INDEX ix_maintenance_drafts_task_id ON maintenance.maintenance_drafts (organization_id, task_id);


CREATE TABLE maintenance.maintenance_orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	summary TEXT NOT NULL, 
	priority TEXT DEFAULT 'medium' NOT NULL, 
	status TEXT DEFAULT 'open' NOT NULL, 
	reported_by_party_id BIGINT, 
	assigned_staff_id BIGINT, 
	vendor_id BIGINT, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (priority IN ('low','medium','high','urgent')), 
	CHECK (status IN ('open','in_progress','completed','cancelled')), 
	UNIQUE (organization_id, reference), 
	CHECK (version > 0)
)

;

CREATE INDEX ix_maintenance_orders_assigned_staff_id ON maintenance.maintenance_orders (organization_id, assigned_staff_id);

CREATE INDEX ix_maintenance_orders_lookup ON maintenance.maintenance_orders (organization_id, property_id, status);

CREATE INDEX ix_maintenance_orders_property_id ON maintenance.maintenance_orders (organization_id, property_id);

CREATE INDEX ix_maintenance_orders_reported_by_party_id ON maintenance.maintenance_orders (organization_id, reported_by_party_id);

CREATE INDEX ix_maintenance_orders_vendor_id ON maintenance.maintenance_orders (organization_id, vendor_id);


CREATE TABLE maintenance.approval_requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	draft_id BIGINT NOT NULL, 
	requested_by BIGINT NOT NULL, 
	reviewer_id BIGINT, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	decision_at TIMESTAMP WITH TIME ZONE, 
	decision_note TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, draft_id) REFERENCES maintenance.maintenance_drafts (organization_id, id), 
	CHECK (status IN ('pending','approved','rejected','cancelled')), 
	CHECK (status NOT IN ('approved','rejected') OR (reviewer_id IS NOT NULL AND decision_at IS NOT NULL))
)

;

CREATE INDEX ix_approval_requests_draft_id ON maintenance.approval_requests (organization_id, draft_id);

CREATE INDEX ix_approval_requests_requested_by ON maintenance.approval_requests (organization_id, requested_by);

CREATE INDEX ix_approval_requests_reviewer_id ON maintenance.approval_requests (organization_id, reviewer_id);


CREATE TABLE maintenance.maintenance_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	order_id BIGINT NOT NULL, 
	actor_staff_id BIGINT NOT NULL, 
	event_type TEXT NOT NULL, 
	details JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, order_id) REFERENCES maintenance.maintenance_orders (organization_id, id)
)

;

CREATE INDEX ix_maintenance_events_actor_staff_id ON maintenance.maintenance_events (organization_id, actor_staff_id);

CREATE INDEX ix_maintenance_events_order_id ON maintenance.maintenance_events (organization_id, order_id);
COMMIT;
