BEGIN;
CREATE SCHEMA property_leasing;


CREATE TABLE property_leasing.parties (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	kind TEXT NOT NULL, 
	user_id BIGINT, 
	name TEXT NOT NULL, 
	contact JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (kind IN ('owner','tenant','prospect','vendor'))
)

;


CREATE TABLE property_leasing.payments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	received_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	provider_reference TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	UNIQUE (organization_id, reference), 
	UNIQUE (organization_id, provider_reference), 
	CHECK (amount > 0)
)

;


CREATE TABLE property_leasing.properties (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	address TEXT NOT NULL, 
	bedrooms INTEGER NOT NULL, 
	bathrooms INTEGER NOT NULL, 
	weekly_rent NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	status TEXT DEFAULT 'available' NOT NULL, 
	listing_visibility TEXT DEFAULT 'private' NOT NULL, 
	attributes JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (status IN ('available','occupied','unavailable')), 
	CHECK (listing_visibility IN ('private','public')), 
	UNIQUE (organization_id, reference), 
	CHECK (bedrooms >= 0), 
	CHECK (bathrooms >= 0), 
	CHECK (weekly_rent >= 0), 
	CHECK (currency ~ '^[A-Z]{3}$')
)

;


CREATE TABLE property_leasing.leases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	starts_on DATE NOT NULL, 
	ends_on DATE NOT NULL, 
	weekly_rent NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	status TEXT DEFAULT 'draft' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	CHECK (status IN ('draft','active','expired','terminated')), 
	UNIQUE (organization_id, reference), 
	CHECK (ends_on >= starts_on), 
	CHECK (weekly_rent >= 0), 
	CHECK (currency ~ '^[A-Z]{3}$')
)

;

CREATE INDEX ix_leases_property_id ON property_leasing.leases (organization_id, property_id);


CREATE TABLE property_leasing.property_favorites (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	party_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, party_id) REFERENCES property_leasing.parties (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	UNIQUE (organization_id, party_id, property_id)
)

;

CREATE INDEX ix_property_favorites_party_id ON property_leasing.property_favorites (organization_id, party_id);

CREATE INDEX ix_property_favorites_property_id ON property_leasing.property_favorites (organization_id, property_id);


CREATE TABLE property_leasing.property_owners (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	party_id BIGINT NOT NULL, 
	share NUMERIC(7, 6) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	FOREIGN KEY(organization_id, party_id) REFERENCES property_leasing.parties (organization_id, id), 
	UNIQUE (organization_id, property_id, party_id), 
	CHECK (share > 0 AND share <= 1)
)

;

CREATE INDEX ix_property_owners_party_id ON property_leasing.property_owners (organization_id, party_id);

CREATE INDEX ix_property_owners_property_id ON property_leasing.property_owners (organization_id, property_id);


CREATE TABLE property_leasing.staff_property_scopes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	staff_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	valid_until TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	UNIQUE (organization_id, staff_id, property_id), 
	CHECK (valid_until IS NULL OR valid_until > valid_from)
)

;

CREATE INDEX ix_staff_property_scopes_property_id ON property_leasing.staff_property_scopes (organization_id, property_id);

CREATE INDEX ix_staff_property_scopes_staff_id ON property_leasing.staff_property_scopes (organization_id, staff_id);


CREATE TABLE property_leasing.tenancy_applications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	applicant_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	status TEXT DEFAULT 'draft' NOT NULL, 
	submitted_at TIMESTAMP WITH TIME ZONE, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	FOREIGN KEY(organization_id, applicant_id) REFERENCES property_leasing.parties (organization_id, id), 
	CHECK (status IN ('draft','submitted','under_review','approved','rejected','withdrawn')), 
	UNIQUE (organization_id, reference), 
	CHECK (version > 0)
)

;

CREATE INDEX ix_tenancy_applications_applicant_id ON property_leasing.tenancy_applications (organization_id, applicant_id);

CREATE INDEX ix_tenancy_applications_property_id ON property_leasing.tenancy_applications (organization_id, property_id);


CREATE TABLE property_leasing.viewing_appointments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	prospect_id BIGINT NOT NULL, 
	host_staff_id BIGINT, 
	starts_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	ends_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	status TEXT DEFAULT 'requested' NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	FOREIGN KEY(organization_id, prospect_id) REFERENCES property_leasing.parties (organization_id, id), 
	CHECK (status IN ('requested','confirmed','completed','cancelled')), 
	UNIQUE (organization_id, idempotency_key), 
	CHECK (ends_at > starts_at)
)

;

CREATE INDEX ix_viewing_appointments_host_staff_id ON property_leasing.viewing_appointments (organization_id, host_staff_id);

CREATE INDEX ix_viewing_appointments_property_id ON property_leasing.viewing_appointments (organization_id, property_id);

CREATE INDEX ix_viewing_appointments_prospect_id ON property_leasing.viewing_appointments (organization_id, prospect_id);


CREATE TABLE property_leasing.lease_tenants (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	lease_id BIGINT NOT NULL, 
	party_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, lease_id) REFERENCES property_leasing.leases (organization_id, id), 
	FOREIGN KEY(organization_id, party_id) REFERENCES property_leasing.parties (organization_id, id), 
	UNIQUE (organization_id, lease_id, party_id)
)

;

CREATE INDEX ix_lease_tenants_lease_id ON property_leasing.lease_tenants (organization_id, lease_id);

CREATE INDEX ix_lease_tenants_party_id ON property_leasing.lease_tenants (organization_id, party_id);


CREATE TABLE property_leasing.rent_invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	lease_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	due_on DATE NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	status TEXT DEFAULT 'issued' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, lease_id) REFERENCES property_leasing.leases (organization_id, id), 
	CHECK (status IN ('issued','void')), 
	UNIQUE (organization_id, reference), 
	CHECK (amount >= 0), 
	CHECK (period_end >= period_start)
)

;

CREATE INDEX ix_rent_invoices_lease_id ON property_leasing.rent_invoices (organization_id, lease_id);

CREATE INDEX ix_rent_invoices_lookup ON property_leasing.rent_invoices (organization_id, lease_id, due_on);


CREATE TABLE property_leasing.payment_allocations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	payment_id BIGINT NOT NULL, 
	invoice_id BIGINT NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, payment_id) REFERENCES property_leasing.payments (organization_id, id), 
	FOREIGN KEY(organization_id, invoice_id) REFERENCES property_leasing.rent_invoices (organization_id, id), 
	UNIQUE (organization_id, payment_id, invoice_id), 
	CHECK (amount > 0)
)

;

CREATE INDEX ix_payment_allocations_invoice_id ON property_leasing.payment_allocations (organization_id, invoice_id);

CREATE INDEX ix_payment_allocations_payment_id ON property_leasing.payment_allocations (organization_id, payment_id);
COMMIT;
