BEGIN;
CREATE SCHEMA staff_agent;


CREATE TABLE staff_agent.agent_definitions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	version TEXT NOT NULL, 
	transport TEXT DEFAULT 'local' NOT NULL, 
	endpoint TEXT, 
	credential_ref TEXT, 
	capabilities JSONB DEFAULT '[]'::jsonb NOT NULL, 
	enabled BOOLEAN DEFAULT false NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (transport IN ('local','a2a')), 
	UNIQUE (organization_id, code, version), 
	CHECK (transport != 'a2a' OR endpoint IS NOT NULL)
)

;


CREATE TABLE staff_agent.outbox_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	event_key TEXT NOT NULL, 
	event_type TEXT NOT NULL, 
	aggregate_type TEXT NOT NULL, 
	aggregate_id BIGINT NOT NULL, 
	payload JSONB NOT NULL, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	attempts INTEGER DEFAULT 0 NOT NULL, 
	available_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (status IN ('pending','delivered','failed')), 
	UNIQUE (organization_id, event_key), 
	CHECK (attempts >= 0)
)

;

CREATE INDEX ix_outbox_events_lookup ON staff_agent.outbox_events (organization_id, status, available_at);


CREATE TABLE staff_agent.staff_sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	staff_id BIGINT NOT NULL, 
	title TEXT DEFAULT '' NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (status IN ('active','archived'))
)

;

CREATE INDEX ix_staff_sessions_staff_id ON staff_agent.staff_sessions (organization_id, staff_id);


CREATE TABLE staff_agent.prompt_versions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	agent_id BIGINT NOT NULL, 
	version TEXT NOT NULL, 
	content TEXT NOT NULL, 
	sha256 TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, agent_id) REFERENCES staff_agent.agent_definitions (organization_id, id), 
	UNIQUE (organization_id, agent_id, version)
)

;

CREATE INDEX ix_prompt_versions_agent_id ON staff_agent.prompt_versions (organization_id, agent_id);


CREATE TABLE staff_agent.staff_requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	session_id BIGINT NOT NULL, 
	original_text TEXT NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	route TEXT DEFAULT 'pending' NOT NULL, 
	status TEXT DEFAULT 'received' NOT NULL, 
	policy_version TEXT DEFAULT 'staff-v2' NOT NULL, 
	route_reason TEXT, 
	final_answer TEXT, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, session_id) REFERENCES staff_agent.staff_sessions (organization_id, id), 
	CHECK (route IN ('pending','execute','human','clarify')), 
	CHECK (status IN ('received','planned','running','completed','partial','failed','needs_input','needs_review')), 
	UNIQUE (organization_id, session_id, idempotency_key)
)

;

CREATE INDEX ix_staff_requests_lookup ON staff_agent.staff_requests (organization_id, session_id, created_at);

CREATE INDEX ix_staff_requests_session_id ON staff_agent.staff_requests (organization_id, session_id);


CREATE TABLE staff_agent.audit_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	actor_staff_id BIGINT, 
	request_id BIGINT, 
	event_type TEXT NOT NULL, 
	resource_type TEXT NOT NULL, 
	resource_id TEXT, 
	details_redacted JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id)
)

;

CREATE INDEX ix_audit_events_actor_staff_id ON staff_agent.audit_events (organization_id, actor_staff_id);

CREATE INDEX ix_audit_events_lookup ON staff_agent.audit_events (organization_id, request_id, created_at);

CREATE INDEX ix_audit_events_request_id ON staff_agent.audit_events (organization_id, request_id);


CREATE TABLE staff_agent.human_cases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	assigned_staff_id BIGINT, 
	reason TEXT NOT NULL, 
	status TEXT DEFAULT 'needs_review' NOT NULL, 
	submission_status TEXT DEFAULT 'not_submitted' NOT NULL, 
	external_reference TEXT, 
	submitted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	CHECK (status IN ('needs_review','queued','in_progress','resolved','cancelled')), 
	CHECK (submission_status IN ('not_submitted','pending','submitted','failed')), 
	UNIQUE (organization_id, request_id), 
	CHECK (submission_status != 'submitted' OR (external_reference IS NOT NULL AND submitted_at IS NOT NULL))
)

;

CREATE INDEX ix_human_cases_assigned_staff_id ON staff_agent.human_cases (organization_id, assigned_staff_id);

CREATE INDEX ix_human_cases_lookup ON staff_agent.human_cases (organization_id, status, created_at);

CREATE INDEX ix_human_cases_request_id ON staff_agent.human_cases (organization_id, request_id);


CREATE TABLE staff_agent.intent_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	prompt_id BIGINT NOT NULL, 
	model TEXT NOT NULL, 
	attempt INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	raw_output JSONB, 
	validation_errors JSONB DEFAULT '[]'::jsonb NOT NULL, 
	latency_ms INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	FOREIGN KEY(organization_id, prompt_id) REFERENCES staff_agent.prompt_versions (organization_id, id), 
	CHECK (status IN ('ok','invalid','error')), 
	UNIQUE (organization_id, request_id, attempt), 
	CHECK (attempt > 0), 
	CHECK (latency_ms IS NULL OR latency_ms >= 0), 
	UNIQUE (organization_id, request_id, id)
)

;

CREATE INDEX ix_intent_runs_prompt_id ON staff_agent.intent_runs (organization_id, prompt_id);

CREATE INDEX ix_intent_runs_request_id ON staff_agent.intent_runs (organization_id, request_id);


CREATE TABLE staff_agent.staff_tasks (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	intent_run_id BIGINT NOT NULL, 
	task_key TEXT NOT NULL, 
	ordinal INTEGER NOT NULL, 
	source_text TEXT NOT NULL, 
	span_start INTEGER NOT NULL, 
	span_end INTEGER NOT NULL, 
	intent TEXT NOT NULL, 
	business_domain TEXT NOT NULL, 
	condition_text TEXT DEFAULT '' NOT NULL, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	parameters JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	FOREIGN KEY(organization_id, intent_run_id) REFERENCES staff_agent.intent_runs (organization_id, id), 
	CHECK (intent IN ('knowledge_question','record_query','action_request','unclear')), 
	CHECK (status IN ('pending','running','ok','denied','unsupported','needs_input','needs_review','failed','skipped')), 
	UNIQUE (organization_id, request_id, task_key), 
	UNIQUE (organization_id, request_id, ordinal), 
	UNIQUE (organization_id, request_id, id), 
	CHECK (ordinal > 0), 
	CHECK (span_start >= 0), 
	CHECK (span_end > span_start), 
	FOREIGN KEY(organization_id, request_id, intent_run_id) REFERENCES staff_agent.intent_runs (organization_id, request_id, id)
)

;

CREATE INDEX ix_staff_tasks_intent_run_id ON staff_agent.staff_tasks (organization_id, intent_run_id);

CREATE INDEX ix_staff_tasks_lookup ON staff_agent.staff_tasks (organization_id, request_id, ordinal);

CREATE INDEX ix_staff_tasks_request_id ON staff_agent.staff_tasks (organization_id, request_id);


CREATE TABLE staff_agent.task_dependencies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	task_id BIGINT NOT NULL, 
	depends_on_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	UNIQUE (organization_id, task_id, depends_on_id), 
	CHECK (task_id != depends_on_id), 
	FOREIGN KEY(organization_id, request_id, task_id) REFERENCES staff_agent.staff_tasks (organization_id, request_id, id), 
	FOREIGN KEY(organization_id, request_id, depends_on_id) REFERENCES staff_agent.staff_tasks (organization_id, request_id, id)
)

;

CREATE INDEX ix_task_dependencies_request_id ON staff_agent.task_dependencies (organization_id, request_id);


CREATE TABLE staff_agent.task_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	task_id BIGINT NOT NULL, 
	agent_id BIGINT, 
	attempt INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	lease_until TIMESTAMP WITH TIME ZONE, 
	worker_id TEXT, 
	error_code TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, task_id) REFERENCES staff_agent.staff_tasks (organization_id, id), 
	FOREIGN KEY(organization_id, agent_id) REFERENCES staff_agent.agent_definitions (organization_id, id), 
	CHECK (status IN ('running','ok','denied','unsupported','needs_input','failed','cancelled')), 
	UNIQUE (organization_id, task_id, attempt), 
	CHECK (attempt > 0), 
	CHECK (finished_at IS NULL OR finished_at >= started_at)
)

;

CREATE INDEX ix_task_runs_agent_id ON staff_agent.task_runs (organization_id, agent_id);

CREATE INDEX ix_task_runs_task_id ON staff_agent.task_runs (organization_id, task_id);

CREATE UNIQUE INDEX uq_task_runs_one_active ON staff_agent.task_runs (organization_id, task_id) WHERE status = 'running';


CREATE TABLE staff_agent.a2a_delegations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	run_id BIGINT NOT NULL, 
	agent_id BIGINT NOT NULL, 
	remote_task_id TEXT, 
	remote_context_id TEXT, 
	protocol_version TEXT NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	last_event_id TEXT, 
	artifacts JSONB DEFAULT '[]'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, run_id) REFERENCES staff_agent.task_runs (organization_id, id), 
	FOREIGN KEY(organization_id, agent_id) REFERENCES staff_agent.agent_definitions (organization_id, id), 
	CHECK (status IN ('pending','working','input_required','completed','failed','cancelled','unknown')), 
	UNIQUE (organization_id, agent_id, remote_task_id), 
	UNIQUE (organization_id, idempotency_key)
)

;

CREATE INDEX ix_a2a_delegations_agent_id ON staff_agent.a2a_delegations (organization_id, agent_id);

CREATE INDEX ix_a2a_delegations_run_id ON staff_agent.a2a_delegations (organization_id, run_id);


CREATE TABLE staff_agent.task_results (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	run_id BIGINT NOT NULL, 
	answer TEXT NOT NULL, 
	data JSONB DEFAULT '{}'::jsonb NOT NULL, 
	source TEXT NOT NULL, 
	business_persisted BOOLEAN DEFAULT false NOT NULL, 
	approval_submitted BOOLEAN DEFAULT false NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, run_id) REFERENCES staff_agent.task_runs (organization_id, id), 
	CHECK (source IN ('mock','business','knowledge')), 
	UNIQUE (organization_id, run_id), 
	CHECK (source != 'mock' OR (NOT business_persisted AND NOT approval_submitted))
)

;

CREATE INDEX ix_task_results_run_id ON staff_agent.task_results (organization_id, run_id);


CREATE TABLE staff_agent.tool_calls (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	run_id BIGINT NOT NULL, 
	call_key TEXT NOT NULL, 
	tool_name TEXT NOT NULL, 
	effect TEXT NOT NULL, 
	authorization_decision TEXT NOT NULL, 
	status TEXT NOT NULL, 
	arguments_redacted JSONB DEFAULT '{}'::jsonb NOT NULL, 
	result_summary JSONB DEFAULT '{}'::jsonb NOT NULL, 
	duration_ms INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, run_id) REFERENCES staff_agent.task_runs (organization_id, id), 
	CHECK (effect IN ('read','draft','write')), 
	CHECK (authorization_decision IN ('allow','deny')), 
	CHECK (status IN ('started','ok','failed','denied')), 
	UNIQUE (organization_id, run_id, call_key), 
	CHECK (authorization_decision != 'deny' OR status = 'denied'), 
	CHECK (duration_ms IS NULL OR duration_ms >= 0)
)

;

CREATE INDEX ix_tool_calls_run_id ON staff_agent.tool_calls (organization_id, run_id);
COMMIT;
