-- GENERATED. Isolated simulation only. No existing public tables modified.

BEGIN;

CREATE SCHEMA identity_access;


CREATE TABLE identity_access.organizations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	name TEXT NOT NULL, 
	code TEXT NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	timezone TEXT DEFAULT 'Asia/Shanghai' NOT NULL, 
	PRIMARY KEY (id), 
	CHECK (status IN ('active','suspended')), 
	UNIQUE (code)
)

;


CREATE TABLE identity_access.account_memberships (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	user_id BIGINT NOT NULL, 
	persona TEXT NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	CHECK (persona IN ('staff','tenant','prospect')), 
	CHECK (status IN ('active','inactive')), 
	UNIQUE (organization_id, user_id, persona)
)

;


CREATE TABLE identity_access.permissions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	description TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	UNIQUE (organization_id, code)
)

;


CREATE TABLE identity_access.roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	UNIQUE (organization_id, code)
)

;


CREATE TABLE identity_access.staff (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	user_id BIGINT, 
	staff_code TEXT NOT NULL, 
	display_name TEXT NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	CHECK (status IN ('active','inactive')), 
	UNIQUE (organization_id, staff_code), 
	UNIQUE (organization_id, user_id)
)

;


CREATE TABLE identity_access.role_permissions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	permission_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	FOREIGN KEY(organization_id, role_id) REFERENCES identity_access.roles (organization_id, id), 
	FOREIGN KEY(organization_id, permission_id) REFERENCES identity_access.permissions (organization_id, id), 
	UNIQUE (organization_id, role_id, permission_id)
)

;

CREATE INDEX ix_role_permissions_permission_id ON identity_access.role_permissions (organization_id, permission_id);

CREATE INDEX ix_role_permissions_role_id ON identity_access.role_permissions (organization_id, role_id);


CREATE TABLE identity_access.staff_roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	staff_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id) REFERENCES identity_access.organizations (id), 
	FOREIGN KEY(organization_id, staff_id) REFERENCES identity_access.staff (organization_id, id), 
	FOREIGN KEY(organization_id, role_id) REFERENCES identity_access.roles (organization_id, id), 
	UNIQUE (organization_id, staff_id, role_id)
)

;

CREATE INDEX ix_staff_roles_role_id ON identity_access.staff_roles (organization_id, role_id);

CREATE INDEX ix_staff_roles_staff_id ON identity_access.staff_roles (organization_id, staff_id);

CREATE SCHEMA property_leasing;


CREATE TABLE property_leasing.parties (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	kind TEXT NOT NULL, 
	user_id BIGINT, 
	name TEXT NOT NULL, 
	contact JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (kind IN ('owner','tenant','prospect','vendor'))
)

;


CREATE TABLE property_leasing.payments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	received_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	provider_reference TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	UNIQUE (organization_id, reference), 
	UNIQUE (organization_id, provider_reference), 
	CHECK (amount > 0)
)

;


CREATE TABLE property_leasing.properties (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	address TEXT NOT NULL, 
	bedrooms INTEGER NOT NULL, 
	bathrooms INTEGER NOT NULL, 
	weekly_rent NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	status TEXT DEFAULT 'available' NOT NULL, 
	listing_visibility TEXT DEFAULT 'private' NOT NULL, 
	attributes JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (status IN ('available','occupied','unavailable')), 
	CHECK (listing_visibility IN ('private','public')), 
	UNIQUE (organization_id, reference), 
	CHECK (bedrooms >= 0), 
	CHECK (bathrooms >= 0), 
	CHECK (weekly_rent >= 0), 
	CHECK (currency ~ '^[A-Z]{3}$')
)

;


CREATE TABLE property_leasing.leases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	starts_on DATE NOT NULL, 
	ends_on DATE NOT NULL, 
	weekly_rent NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	status TEXT DEFAULT 'draft' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	CHECK (status IN ('draft','active','expired','terminated')), 
	UNIQUE (organization_id, reference), 
	CHECK (ends_on >= starts_on), 
	CHECK (weekly_rent >= 0), 
	CHECK (currency ~ '^[A-Z]{3}$')
)

;

CREATE INDEX ix_leases_property_id ON property_leasing.leases (organization_id, property_id);


CREATE TABLE property_leasing.property_favorites (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	party_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, party_id) REFERENCES property_leasing.parties (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	UNIQUE (organization_id, party_id, property_id)
)

;

CREATE INDEX ix_property_favorites_party_id ON property_leasing.property_favorites (organization_id, party_id);

CREATE INDEX ix_property_favorites_property_id ON property_leasing.property_favorites (organization_id, property_id);


CREATE TABLE property_leasing.property_owners (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	party_id BIGINT NOT NULL, 
	share NUMERIC(7, 6) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	FOREIGN KEY(organization_id, party_id) REFERENCES property_leasing.parties (organization_id, id), 
	UNIQUE (organization_id, property_id, party_id), 
	CHECK (share > 0 AND share <= 1)
)

;

CREATE INDEX ix_property_owners_party_id ON property_leasing.property_owners (organization_id, party_id);

CREATE INDEX ix_property_owners_property_id ON property_leasing.property_owners (organization_id, property_id);


CREATE TABLE property_leasing.staff_property_scopes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	staff_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	valid_until TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	UNIQUE (organization_id, staff_id, property_id), 
	CHECK (valid_until IS NULL OR valid_until > valid_from)
)

;

CREATE INDEX ix_staff_property_scopes_property_id ON property_leasing.staff_property_scopes (organization_id, property_id);

CREATE INDEX ix_staff_property_scopes_staff_id ON property_leasing.staff_property_scopes (organization_id, staff_id);


CREATE TABLE property_leasing.tenancy_applications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	applicant_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	status TEXT DEFAULT 'draft' NOT NULL, 
	submitted_at TIMESTAMP WITH TIME ZONE, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	FOREIGN KEY(organization_id, applicant_id) REFERENCES property_leasing.parties (organization_id, id), 
	CHECK (status IN ('draft','submitted','under_review','approved','rejected','withdrawn')), 
	UNIQUE (organization_id, reference), 
	CHECK (version > 0)
)

;

CREATE INDEX ix_tenancy_applications_applicant_id ON property_leasing.tenancy_applications (organization_id, applicant_id);

CREATE INDEX ix_tenancy_applications_property_id ON property_leasing.tenancy_applications (organization_id, property_id);


CREATE TABLE property_leasing.viewing_appointments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	prospect_id BIGINT NOT NULL, 
	host_staff_id BIGINT, 
	starts_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	ends_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	status TEXT DEFAULT 'requested' NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, property_id) REFERENCES property_leasing.properties (organization_id, id), 
	FOREIGN KEY(organization_id, prospect_id) REFERENCES property_leasing.parties (organization_id, id), 
	CHECK (status IN ('requested','confirmed','completed','cancelled')), 
	UNIQUE (organization_id, idempotency_key), 
	CHECK (ends_at > starts_at)
)

;

CREATE INDEX ix_viewing_appointments_host_staff_id ON property_leasing.viewing_appointments (organization_id, host_staff_id);

CREATE INDEX ix_viewing_appointments_property_id ON property_leasing.viewing_appointments (organization_id, property_id);

CREATE INDEX ix_viewing_appointments_prospect_id ON property_leasing.viewing_appointments (organization_id, prospect_id);


CREATE TABLE property_leasing.lease_tenants (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	lease_id BIGINT NOT NULL, 
	party_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, lease_id) REFERENCES property_leasing.leases (organization_id, id), 
	FOREIGN KEY(organization_id, party_id) REFERENCES property_leasing.parties (organization_id, id), 
	UNIQUE (organization_id, lease_id, party_id)
)

;

CREATE INDEX ix_lease_tenants_lease_id ON property_leasing.lease_tenants (organization_id, lease_id);

CREATE INDEX ix_lease_tenants_party_id ON property_leasing.lease_tenants (organization_id, party_id);


CREATE TABLE property_leasing.rent_invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	lease_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	due_on DATE NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	currency TEXT DEFAULT 'AUD' NOT NULL, 
	status TEXT DEFAULT 'issued' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, lease_id) REFERENCES property_leasing.leases (organization_id, id), 
	CHECK (status IN ('issued','void')), 
	UNIQUE (organization_id, reference), 
	CHECK (amount >= 0), 
	CHECK (period_end >= period_start)
)

;

CREATE INDEX ix_rent_invoices_lease_id ON property_leasing.rent_invoices (organization_id, lease_id);

CREATE INDEX ix_rent_invoices_lookup ON property_leasing.rent_invoices (organization_id, lease_id, due_on);


CREATE TABLE property_leasing.payment_allocations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	payment_id BIGINT NOT NULL, 
	invoice_id BIGINT NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, payment_id) REFERENCES property_leasing.payments (organization_id, id), 
	FOREIGN KEY(organization_id, invoice_id) REFERENCES property_leasing.rent_invoices (organization_id, id), 
	UNIQUE (organization_id, payment_id, invoice_id), 
	CHECK (amount > 0)
)

;

CREATE INDEX ix_payment_allocations_invoice_id ON property_leasing.payment_allocations (organization_id, invoice_id);

CREATE INDEX ix_payment_allocations_payment_id ON property_leasing.payment_allocations (organization_id, payment_id);

CREATE SCHEMA maintenance;


CREATE TABLE maintenance.maintenance_drafts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	task_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	created_by BIGINT NOT NULL, 
	summary TEXT NOT NULL, 
	priority TEXT DEFAULT 'medium' NOT NULL, 
	mode TEXT DEFAULT 'mock' NOT NULL, 
	status TEXT DEFAULT 'simulated' NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (priority IN ('low','medium','high','urgent')), 
	CHECK (mode IN ('mock','live')), 
	CHECK (status IN ('simulated','draft','submitted','discarded')), 
	UNIQUE (organization_id, idempotency_key), 
	CHECK (mode != 'mock' OR status IN ('simulated','discarded'))
)

;

CREATE INDEX ix_maintenance_drafts_created_by ON maintenance.maintenance_drafts (organization_id, created_by);

CREATE INDEX ix_maintenance_drafts_property_id ON maintenance.maintenance_drafts (organization_id, property_id);

CREATE INDEX ix_maintenance_drafts_task_id ON maintenance.maintenance_drafts (organization_id, task_id);


CREATE TABLE maintenance.maintenance_orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	reference TEXT NOT NULL, 
	summary TEXT NOT NULL, 
	priority TEXT DEFAULT 'medium' NOT NULL, 
	status TEXT DEFAULT 'open' NOT NULL, 
	reported_by_party_id BIGINT, 
	assigned_staff_id BIGINT, 
	vendor_id BIGINT, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (priority IN ('low','medium','high','urgent')), 
	CHECK (status IN ('open','in_progress','completed','cancelled')), 
	UNIQUE (organization_id, reference), 
	CHECK (version > 0)
)

;

CREATE INDEX ix_maintenance_orders_assigned_staff_id ON maintenance.maintenance_orders (organization_id, assigned_staff_id);

CREATE INDEX ix_maintenance_orders_lookup ON maintenance.maintenance_orders (organization_id, property_id, status);

CREATE INDEX ix_maintenance_orders_property_id ON maintenance.maintenance_orders (organization_id, property_id);

CREATE INDEX ix_maintenance_orders_reported_by_party_id ON maintenance.maintenance_orders (organization_id, reported_by_party_id);

CREATE INDEX ix_maintenance_orders_vendor_id ON maintenance.maintenance_orders (organization_id, vendor_id);


CREATE TABLE maintenance.approval_requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	draft_id BIGINT NOT NULL, 
	requested_by BIGINT NOT NULL, 
	reviewer_id BIGINT, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	decision_at TIMESTAMP WITH TIME ZONE, 
	decision_note TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, draft_id) REFERENCES maintenance.maintenance_drafts (organization_id, id), 
	CHECK (status IN ('pending','approved','rejected','cancelled')), 
	CHECK (status NOT IN ('approved','rejected') OR (reviewer_id IS NOT NULL AND decision_at IS NOT NULL))
)

;

CREATE INDEX ix_approval_requests_draft_id ON maintenance.approval_requests (organization_id, draft_id);

CREATE INDEX ix_approval_requests_requested_by ON maintenance.approval_requests (organization_id, requested_by);

CREATE INDEX ix_approval_requests_reviewer_id ON maintenance.approval_requests (organization_id, reviewer_id);


CREATE TABLE maintenance.maintenance_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	order_id BIGINT NOT NULL, 
	actor_staff_id BIGINT NOT NULL, 
	event_type TEXT NOT NULL, 
	details JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, order_id) REFERENCES maintenance.maintenance_orders (organization_id, id)
)

;

CREATE INDEX ix_maintenance_events_actor_staff_id ON maintenance.maintenance_events (organization_id, actor_staff_id);

CREATE INDEX ix_maintenance_events_order_id ON maintenance.maintenance_events (organization_id, order_id);

CREATE SCHEMA inspection_report;


CREATE TABLE inspection_report.inspections (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	property_id BIGINT NOT NULL, 
	inspector_id BIGINT, 
	kind TEXT NOT NULL, 
	inspected_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	status TEXT DEFAULT 'scheduled' NOT NULL, 
	summary TEXT DEFAULT '' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (kind IN ('routine','move_in','move_out','video')), 
	CHECK (status IN ('scheduled','completed','cancelled'))
)

;

CREATE INDEX ix_inspections_inspector_id ON inspection_report.inspections (organization_id, inspector_id);

CREATE INDEX ix_inspections_lookup ON inspection_report.inspections (organization_id, property_id, inspected_at);

CREATE INDEX ix_inspections_property_id ON inspection_report.inspections (organization_id, property_id);


CREATE TABLE inspection_report.inspection_findings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	inspection_id BIGINT NOT NULL, 
	area TEXT NOT NULL, 
	description TEXT NOT NULL, 
	severity TEXT NOT NULL, 
	evidence JSONB DEFAULT '[]'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, inspection_id) REFERENCES inspection_report.inspections (organization_id, id), 
	CHECK (severity IN ('info','low','medium','high','critical'))
)

;

CREATE INDEX ix_inspection_findings_inspection_id ON inspection_report.inspection_findings (organization_id, inspection_id);


CREATE TABLE inspection_report.inspection_reports (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	inspection_id BIGINT NOT NULL, 
	report_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, inspection_id) REFERENCES inspection_report.inspections (organization_id, id), 
	UNIQUE (organization_id, inspection_id, report_id)
)

;

CREATE INDEX ix_inspection_reports_inspection_id ON inspection_report.inspection_reports (organization_id, inspection_id);


CREATE TABLE inspection_report.report_jobs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	requested_by_user_id BIGINT NOT NULL, 
	input_file_id BIGINT NOT NULL, 
	report_id BIGINT, 
	inspection_id BIGINT, 
	status TEXT DEFAULT 'queued' NOT NULL, 
	validation_passed BOOLEAN, 
	idempotency_key TEXT NOT NULL, 
	pipeline_version TEXT NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, inspection_id) REFERENCES inspection_report.inspections (organization_id, id), 
	CHECK (status IN ('queued','running','completed','failed','cancelled')), 
	UNIQUE (organization_id, requested_by_user_id, idempotency_key)
)

;

CREATE INDEX ix_report_jobs_inspection_id ON inspection_report.report_jobs (organization_id, inspection_id);


CREATE TABLE inspection_report.report_job_steps (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	job_id BIGINT NOT NULL, 
	step_name TEXT NOT NULL, 
	attempt INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	metrics JSONB DEFAULT '{}'::jsonb NOT NULL, 
	error_code TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, job_id) REFERENCES inspection_report.report_jobs (organization_id, id), 
	CHECK (status IN ('running','completed','failed','skipped')), 
	UNIQUE (organization_id, job_id, step_name, attempt), 
	CHECK (attempt > 0)
)

;

CREATE INDEX ix_report_job_steps_job_id ON inspection_report.report_job_steps (organization_id, job_id);

CREATE SCHEMA knowledge;


CREATE TABLE knowledge.knowledge_bases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	name TEXT NOT NULL, 
	audience TEXT DEFAULT 'staff' NOT NULL, 
	retrieval_provider TEXT NOT NULL, 
	external_dataset_id TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (audience IN ('staff','tenant','public')), 
	UNIQUE (organization_id, code)
)

;


CREATE TABLE knowledge.knowledge_documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	knowledge_base_id BIGINT NOT NULL, 
	document_key TEXT NOT NULL, 
	version INTEGER NOT NULL, 
	title TEXT NOT NULL, 
	file_id BIGINT, 
	external_document_id TEXT, 
	status TEXT DEFAULT 'draft' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, knowledge_base_id) REFERENCES knowledge.knowledge_bases (organization_id, id), 
	CHECK (status IN ('draft','published','retired')), 
	UNIQUE (organization_id, knowledge_base_id, document_key, version), 
	CHECK (version > 0)
)

;

CREATE INDEX ix_knowledge_documents_knowledge_base_id ON knowledge.knowledge_documents (organization_id, knowledge_base_id);


CREATE TABLE knowledge.knowledge_role_access (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	knowledge_base_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, knowledge_base_id) REFERENCES knowledge.knowledge_bases (organization_id, id), 
	UNIQUE (organization_id, knowledge_base_id, role_id)
)

;

CREATE INDEX ix_knowledge_role_access_knowledge_base_id ON knowledge.knowledge_role_access (organization_id, knowledge_base_id);

CREATE INDEX ix_knowledge_role_access_role_id ON knowledge.knowledge_role_access (organization_id, role_id);

CREATE SCHEMA staff_agent;


CREATE TABLE staff_agent.agent_definitions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	code TEXT NOT NULL, 
	version TEXT NOT NULL, 
	transport TEXT DEFAULT 'local' NOT NULL, 
	endpoint TEXT, 
	credential_ref TEXT, 
	capabilities JSONB DEFAULT '[]'::jsonb NOT NULL, 
	enabled BOOLEAN DEFAULT false NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (transport IN ('local','a2a')), 
	UNIQUE (organization_id, code, version), 
	CHECK (transport != 'a2a' OR endpoint IS NOT NULL)
)

;


CREATE TABLE staff_agent.outbox_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	event_key TEXT NOT NULL, 
	event_type TEXT NOT NULL, 
	aggregate_type TEXT NOT NULL, 
	aggregate_id BIGINT NOT NULL, 
	payload JSONB NOT NULL, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	attempts INTEGER DEFAULT 0 NOT NULL, 
	available_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (status IN ('pending','delivered','failed')), 
	UNIQUE (organization_id, event_key), 
	CHECK (attempts >= 0)
)

;

CREATE INDEX ix_outbox_events_lookup ON staff_agent.outbox_events (organization_id, status, available_at);


CREATE TABLE staff_agent.staff_sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	staff_id BIGINT NOT NULL, 
	title TEXT DEFAULT '' NOT NULL, 
	status TEXT DEFAULT 'active' NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	CHECK (status IN ('active','archived'))
)

;

CREATE INDEX ix_staff_sessions_staff_id ON staff_agent.staff_sessions (organization_id, staff_id);


CREATE TABLE staff_agent.prompt_versions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	agent_id BIGINT NOT NULL, 
	version TEXT NOT NULL, 
	content TEXT NOT NULL, 
	sha256 TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, agent_id) REFERENCES staff_agent.agent_definitions (organization_id, id), 
	UNIQUE (organization_id, agent_id, version)
)

;

CREATE INDEX ix_prompt_versions_agent_id ON staff_agent.prompt_versions (organization_id, agent_id);


CREATE TABLE staff_agent.staff_requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	session_id BIGINT NOT NULL, 
	original_text TEXT NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	route TEXT DEFAULT 'pending' NOT NULL, 
	status TEXT DEFAULT 'received' NOT NULL, 
	policy_version TEXT DEFAULT 'staff-v2' NOT NULL, 
	route_reason TEXT, 
	final_answer TEXT, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, session_id) REFERENCES staff_agent.staff_sessions (organization_id, id), 
	CHECK (route IN ('pending','execute','human','clarify')), 
	CHECK (status IN ('received','planned','running','completed','partial','failed','needs_input','needs_review')), 
	UNIQUE (organization_id, session_id, idempotency_key)
)

;

CREATE INDEX ix_staff_requests_lookup ON staff_agent.staff_requests (organization_id, session_id, created_at);

CREATE INDEX ix_staff_requests_session_id ON staff_agent.staff_requests (organization_id, session_id);


CREATE TABLE staff_agent.audit_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	actor_staff_id BIGINT, 
	request_id BIGINT, 
	event_type TEXT NOT NULL, 
	resource_type TEXT NOT NULL, 
	resource_id TEXT, 
	details_redacted JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id)
)

;

CREATE INDEX ix_audit_events_actor_staff_id ON staff_agent.audit_events (organization_id, actor_staff_id);

CREATE INDEX ix_audit_events_lookup ON staff_agent.audit_events (organization_id, request_id, created_at);

CREATE INDEX ix_audit_events_request_id ON staff_agent.audit_events (organization_id, request_id);


CREATE TABLE staff_agent.human_cases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	assigned_staff_id BIGINT, 
	reason TEXT NOT NULL, 
	status TEXT DEFAULT 'needs_review' NOT NULL, 
	submission_status TEXT DEFAULT 'not_submitted' NOT NULL, 
	external_reference TEXT, 
	submitted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	CHECK (status IN ('needs_review','queued','in_progress','resolved','cancelled')), 
	CHECK (submission_status IN ('not_submitted','pending','submitted','failed')), 
	UNIQUE (organization_id, request_id), 
	CHECK (submission_status != 'submitted' OR (external_reference IS NOT NULL AND submitted_at IS NOT NULL))
)

;

CREATE INDEX ix_human_cases_assigned_staff_id ON staff_agent.human_cases (organization_id, assigned_staff_id);

CREATE INDEX ix_human_cases_lookup ON staff_agent.human_cases (organization_id, status, created_at);

CREATE INDEX ix_human_cases_request_id ON staff_agent.human_cases (organization_id, request_id);


CREATE TABLE staff_agent.intent_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	prompt_id BIGINT NOT NULL, 
	model TEXT NOT NULL, 
	attempt INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	raw_output JSONB, 
	validation_errors JSONB DEFAULT '[]'::jsonb NOT NULL, 
	latency_ms INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	FOREIGN KEY(organization_id, prompt_id) REFERENCES staff_agent.prompt_versions (organization_id, id), 
	CHECK (status IN ('ok','invalid','error')), 
	UNIQUE (organization_id, request_id, attempt), 
	CHECK (attempt > 0), 
	CHECK (latency_ms IS NULL OR latency_ms >= 0), 
	UNIQUE (organization_id, request_id, id)
)

;

CREATE INDEX ix_intent_runs_prompt_id ON staff_agent.intent_runs (organization_id, prompt_id);

CREATE INDEX ix_intent_runs_request_id ON staff_agent.intent_runs (organization_id, request_id);


CREATE TABLE staff_agent.staff_tasks (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	intent_run_id BIGINT NOT NULL, 
	task_key TEXT NOT NULL, 
	ordinal INTEGER NOT NULL, 
	source_text TEXT NOT NULL, 
	span_start INTEGER NOT NULL, 
	span_end INTEGER NOT NULL, 
	intent TEXT NOT NULL, 
	business_domain TEXT NOT NULL, 
	condition_text TEXT DEFAULT '' NOT NULL, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	parameters JSONB DEFAULT '{}'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	FOREIGN KEY(organization_id, intent_run_id) REFERENCES staff_agent.intent_runs (organization_id, id), 
	CHECK (intent IN ('knowledge_question','record_query','action_request','unclear')), 
	CHECK (status IN ('pending','running','ok','denied','unsupported','needs_input','needs_review','failed','skipped')), 
	UNIQUE (organization_id, request_id, task_key), 
	UNIQUE (organization_id, request_id, ordinal), 
	UNIQUE (organization_id, request_id, id), 
	CHECK (ordinal > 0), 
	CHECK (span_start >= 0), 
	CHECK (span_end > span_start), 
	FOREIGN KEY(organization_id, request_id, intent_run_id) REFERENCES staff_agent.intent_runs (organization_id, request_id, id)
)

;

CREATE INDEX ix_staff_tasks_intent_run_id ON staff_agent.staff_tasks (organization_id, intent_run_id);

CREATE INDEX ix_staff_tasks_lookup ON staff_agent.staff_tasks (organization_id, request_id, ordinal);

CREATE INDEX ix_staff_tasks_request_id ON staff_agent.staff_tasks (organization_id, request_id);


CREATE TABLE staff_agent.task_dependencies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	request_id BIGINT NOT NULL, 
	task_id BIGINT NOT NULL, 
	depends_on_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, request_id) REFERENCES staff_agent.staff_requests (organization_id, id), 
	UNIQUE (organization_id, task_id, depends_on_id), 
	CHECK (task_id != depends_on_id), 
	FOREIGN KEY(organization_id, request_id, task_id) REFERENCES staff_agent.staff_tasks (organization_id, request_id, id), 
	FOREIGN KEY(organization_id, request_id, depends_on_id) REFERENCES staff_agent.staff_tasks (organization_id, request_id, id)
)

;

CREATE INDEX ix_task_dependencies_request_id ON staff_agent.task_dependencies (organization_id, request_id);


CREATE TABLE staff_agent.task_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	task_id BIGINT NOT NULL, 
	agent_id BIGINT, 
	attempt INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	lease_until TIMESTAMP WITH TIME ZONE, 
	worker_id TEXT, 
	error_code TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, task_id) REFERENCES staff_agent.staff_tasks (organization_id, id), 
	FOREIGN KEY(organization_id, agent_id) REFERENCES staff_agent.agent_definitions (organization_id, id), 
	CHECK (status IN ('running','ok','denied','unsupported','needs_input','failed','cancelled')), 
	UNIQUE (organization_id, task_id, attempt), 
	CHECK (attempt > 0), 
	CHECK (finished_at IS NULL OR finished_at >= started_at)
)

;

CREATE INDEX ix_task_runs_agent_id ON staff_agent.task_runs (organization_id, agent_id);

CREATE INDEX ix_task_runs_task_id ON staff_agent.task_runs (organization_id, task_id);

CREATE UNIQUE INDEX uq_task_runs_one_active ON staff_agent.task_runs (organization_id, task_id) WHERE status = 'running';


CREATE TABLE staff_agent.a2a_delegations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	run_id BIGINT NOT NULL, 
	agent_id BIGINT NOT NULL, 
	remote_task_id TEXT, 
	remote_context_id TEXT, 
	protocol_version TEXT NOT NULL, 
	idempotency_key TEXT NOT NULL, 
	status TEXT DEFAULT 'pending' NOT NULL, 
	last_event_id TEXT, 
	artifacts JSONB DEFAULT '[]'::jsonb NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, run_id) REFERENCES staff_agent.task_runs (organization_id, id), 
	FOREIGN KEY(organization_id, agent_id) REFERENCES staff_agent.agent_definitions (organization_id, id), 
	CHECK (status IN ('pending','working','input_required','completed','failed','cancelled','unknown')), 
	UNIQUE (organization_id, agent_id, remote_task_id), 
	UNIQUE (organization_id, idempotency_key)
)

;

CREATE INDEX ix_a2a_delegations_agent_id ON staff_agent.a2a_delegations (organization_id, agent_id);

CREATE INDEX ix_a2a_delegations_run_id ON staff_agent.a2a_delegations (organization_id, run_id);


CREATE TABLE staff_agent.task_results (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	run_id BIGINT NOT NULL, 
	answer TEXT NOT NULL, 
	data JSONB DEFAULT '{}'::jsonb NOT NULL, 
	source TEXT NOT NULL, 
	business_persisted BOOLEAN DEFAULT false NOT NULL, 
	approval_submitted BOOLEAN DEFAULT false NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, run_id) REFERENCES staff_agent.task_runs (organization_id, id), 
	CHECK (source IN ('mock','business','knowledge')), 
	UNIQUE (organization_id, run_id), 
	CHECK (source != 'mock' OR (NOT business_persisted AND NOT approval_submitted))
)

;

CREATE INDEX ix_task_results_run_id ON staff_agent.task_results (organization_id, run_id);


CREATE TABLE staff_agent.tool_calls (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	organization_id BIGINT NOT NULL, 
	run_id BIGINT NOT NULL, 
	call_key TEXT NOT NULL, 
	tool_name TEXT NOT NULL, 
	effect TEXT NOT NULL, 
	authorization_decision TEXT NOT NULL, 
	status TEXT NOT NULL, 
	arguments_redacted JSONB DEFAULT '{}'::jsonb NOT NULL, 
	result_summary JSONB DEFAULT '{}'::jsonb NOT NULL, 
	duration_ms INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (organization_id, id), 
	FOREIGN KEY(organization_id, run_id) REFERENCES staff_agent.task_runs (organization_id, id), 
	CHECK (effect IN ('read','draft','write')), 
	CHECK (authorization_decision IN ('allow','deny')), 
	CHECK (status IN ('started','ok','failed','denied')), 
	UNIQUE (organization_id, run_id, call_key), 
	CHECK (authorization_decision != 'deny' OR status = 'denied'), 
	CHECK (duration_ms IS NULL OR duration_ms >= 0)
)

;

CREATE INDEX ix_tool_calls_run_id ON staff_agent.tool_calls (organization_id, run_id);

COMMIT;
